### ISSUE TITLE
Didn't show scoreboard

### ISSUE THREAD

**Issue by liziyi0914** [PetteriM1/SimpleScoreboards#1]
console
![screenshot_20190214-023817](https://user-images.githubusercontent.com/15710163/52735171-f11fbb80-3001-11e9-8ee9-3f2cc1292f44.jpg)
![screenshot_20190214-023822](https://user-images.githubusercontent.com/15710163/52735236-190f1f00-3002-11e9-8796-73f1772ac6ef.jpg)
it thew this exception

plugins I installed
KotlinLib v1.0, MobPlugin v1.6, DbLib v0.2.2, SimpleScoreboards v2.2, ScoreboardPlugin v1.0, FastAsyncWorldEdit v19.01.12-dc2d277-1245-22.0.7, PlaceholderAPI v1.2

**Comment by PetteriM1** [comment]
This is because the ScoreboardAPI isn't updated to work with latest NukkitX. Need to wait that @TheAmyChan98 updates it.

**Comment by PetteriM1** [comment]
Download latest ScoreboardAPI from here: [https://nukkitx.com/resources/scoreboardapi.181/](https://nukkitx.com/resources/scoreboardapi.181/)
