### ISSUE TITLE
no scoreboard world is not working

### ISSUE THREAD

**Issue by Sreeraj-S** [PetteriM1/SimpleScoreboards#12]
![Screenshot (83)_LI](https://user-images.githubusercontent.com/56246216/115871382-191acd00-a45e-11eb-8621-2c4a69938c11.jpg)

**Comment by PetteriM1** [comment]
In fact it is working even though it doesn't currently have an option to automatically remove existing scoreboard on world change

**Comment by Sreeraj-S** [comment]
oh, I see. Hope you will fix it next update.

**Comment by PetteriM1** [comment]
Fixed in version 2.5.0
