### ISSUE TITLE
This is not a bug report, but please read it all.

### ISSUE THREAD

**Issue by chicuong2412** [PetteriM1/SimpleScoreboards#2]
I sincerely apologize for this, because it is not an error report.
I would like to suggest you an idea to add to SimpleScoreboards.
Please add the MVdwPlaceholderAPI support
This is a Spigot plugin that runs using Pokkit.

**Comment by PetteriM1** [comment]
It's not worth trying to implement support for any Spigot plugin into this plugin. You can use placeholders from Nukkit's PlaceholderAPI plugin.
